void setuphorn();
void horn();
void testhorn();

void setupLED();
void testLED();
void brakeLED();
void driveLED();
void rightLED();
void leftLED();
void setupArdumoto();
void testArdumoto();
void driveArdumoto(byte motor, byte dir, byte spd);
void stopArdumoto(byte motor);
void forward();
void backward();
void right();
void left();
void stopMotors();
void setupProximity();
void testProximity();
void setupServo();
void testServo();
